version: "3"

services:
    web:
        build: .devcontainer
        ports:
            - "3000:3000"
        environment:
            - "DATABASE_HOST=db"
            - "DATABASE_PORT=5432"
            - "DATABASE_USER=postgres"
            - "DATABASE_PASSWORD=password"
        links:
            - db
        volumes:
            - ".:/app"
        stdin_open: true

    db:
        image: postgres:12.3
        ports:
            - "4000:5432"
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=password"

    smtp:
        image: schickling/mailcatcher
        ports:
        - "1080:1080"
        - "1025:1025"

    redis:
        image: redis:latest
        ports:
        - "6379:6379"
        command: redis-server
        volumes:
        - ./data/redis:/data
